# Generated by Django 5.1.3 on 2025-02-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
    ]
